### POST Create Order
POST https://ticketing.com/api/orders
Content-Type: application/json

{
  "ticketId": "66f977958967aa2666686dc0"
}

### GET Show Order
GET https://ticketing.com/api/orders/66f9779c89a0224e7d8bc0b6

### GET All Tickets
GET https://ticketing.com/api/orders

### PUT Update Order
PUT https://ticketing.com/api/orders/66e17122ec50bddeb53b7614
Content-Type: application/json

{
  "title": "Soccer",
  "price": 15
}
