name: test-tickets

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies and Run Tests in tickets/
        run: cd tickets && npm install && npm run test:ci
