name: Auth Tests

on:
  pull_request:
    branches:
     - master
  workflow_dispatch:

jobs:
  build:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Change Directory to auth/
        run: cd auth

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test:ci
