name: Auth Tests

on:
  pull_request:
    branches:
     - master
  workflow_dispatch:

jobs:
  build:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies and Run Tests in auth/
        run: |
          cd auth
          npm install
          npm test:ci
