name: test-orders

on:
  pull_request:
    paths:
      - "orders/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies and Run Tests in orders/
        run: cd orders && npm install && npm run test:ci
