name: test-auth

on:
  pull_request:
    paths:
      - "auth/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies and Run Tests in auth/
        run: cd auth && npm install && npm run test:ci
